# Install modern linux terminal commands
---
- name: Install command line tools
  become: true
  vars:
    user: "{{ lookup('env', 'USER') }}"
  block:
    - name: Download zoxide installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
        dest: /tmp/zoxide-install.sh
        mode: 0755

    - name: Execute the zoxide-install.sh
      ansible.builtin.command: /tmp/zoxide-install.sh
      changed_when: false

    - name: Remove the zoxide-install.sh
      ansible.builtin.file:
        path: /tmp/zoxide-install.sh
        state: absent

    - name: Install fd
      ansible.builtin.apt:
        state: present
        pkg:
          - fd-find
        update_cache: true
        cache_valid_time: 3600
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install bat
      ansible.builtin.apt:
        state: present
        pkg:
          - bat
        update_cache: true
        cache_valid_time: 3600
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install ripgrep
      ansible.builtin.apt:
        state: present
        pkg:
          - ripgrep
        update_cache: true
        cache_valid_time: 3600
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install tldr
      ansible.builtin.apt:
        state: present
        pkg:
          - tldr
        update_cache: true
        cache_valid_time: 3600
      register: apt_res
      retries: 5
      until: apt_res is success

      # - name: Install cargo
      # shell:
      # cmd: curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
    - name: Check if cargo is installed
      ansible.builtin.command: command -v cargo
      register: cargo_exists
      ignore_errors: true
      changed_when: cargo_exists.rc != 0

    - name: Download installer
      when: cargo_exists is failed
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: Install rust/cargo
      when: cargo_exists is failed
      ansible.builtin.command: /tmp/sh.rustup.rs -y
      tags:
        - rust

    - name: Install sd package
      community.general.cargo:
        name: sd

        # - name: difftastic
        # community.general.snap:
        # state: present
        # name:
        # - difftastic
        # update_cache: yes
        # cache_valid_time: 3600
        # register: apt_res
        # retries: 5
        # until: apt_res is success
